apiVersion: apps/v1
kind: Deployment
metadata:
  name: contoso-names-service
  labels:
    app: contoso-names-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: contoso-names-service
  template:
    metadata:
      labels:
        app: contoso-names-service
    spec:
      containers:
        - name: contoso-names-service
          image: ywregistry1114.azurecr.io/contoso-names-service:v1
          ports:
            - containerPort: 80